### ISSUE TITLE
[Setting] 프로젝트 세팅

### ISSUE THREAD

**Issue by lsh328328** [Travalue/Travalue-Server#1]
## 💡 About

프로젝트 및 깃허브 기본 세팅

## 📝 To Do

- [x] Spring initializer로 프로젝트 기본 세팅
- [x] 깃허브 템플릿 및 라벨 생성

## ✅ Issue check list

- [x] Assignees, Labels 확인하기

**Comment by tykwon97** [comment]
Label 만드느라 고생했겠다😅 이모티콘이랑 같이 Label 하니까 깔끔하네 좋다!!
